<a href="https://colab.research.google.com/github/profteachkids/CHE2064_Spring2023/blob/main/BenzeneTolueneVLECalculation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!wget -N -q https://raw.githubusercontent.com/profteachkids/chetools/main/tools/che4.ipynb -O che4.ipynb
!python -m pip install importnb --quiet
from importnb import Notebook
with Notebook():
    from che4 import Range, Comp, CompArray, RangeArray, DotDict, d2nt, Props

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.9/42.9 kB 1.6 MB/s eta 0:00:00


In [39]:
import numpy as np
from plotly.subplots import make_subplots

In [7]:
p=Props(['Benzene','Toluene'])

In [20]:
def bubbleP(x, T):
    pi= x*p.Pvap(T)
    ptot=np.sum(pi)
    return ptot, pi/ptot

In [33]:
z=np.array([0.4,0.6])

In [22]:
def dewP(y, T):
    P=1/np.sum(y/p.Pvap(T))
    x = y*P/p.Pvap(T)
    return P, x

In [24]:
dewP(z,80+273)

(Array(51140.99477745, dtype=float64),
 Array([0.20363048, 0.79636952], dtype=float64))

In [25]:
bubbleP(z,80+273)

(Array(63301.73149713, dtype=float64),
 Array([0.63479101, 0.36520899], dtype=float64))

In [26]:
p.Pvap(80+273)

Array([100458.42569497,  38530.6020319 ], dtype=float64)

In [32]:
z1s=np.linspace(0,1,11)
zs=np.c_[z1,1-z1]

In [44]:
z1s

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [45]:
x1s,y1s,bPs,dPs=[],[],[],[]
T=80+273.15
for z in zs:
    bP,y= bubbleP(z,T)
    dP,x = dewP(z,T)
    x1s.append(x[0])
    y1s.append(y[0])
    bPs.append(bP)
    dPs.append(dP)

In [48]:
fig=make_subplots()
fig.add_scatter(x=z1s,y=bPs,name='bubble')
fig.add_scatter(x=z1s,y=dPs,name='dew')
fig.update_layout(width=800,height=600,template='plotly_dark',title='T=353 K')