<a href="https://colab.research.google.com/github/profteachkids/CHE2064_Spring2023/blob/main/BenzeneTolueneVLECalculation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!wget -N -q https://raw.githubusercontent.com/profteachkids/chetools/main/tools/che4.ipynb -O che4.ipynb
!python -m pip install importnb --quiet
from importnb import Notebook
with Notebook():
    from che4 import Range, Comp, CompArray, RangeArray, DotDict, d2nt, Props

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.9/42.9 kB 1.2 MB/s eta 0:00:00


In [2]:
import numpy as np
from plotly.subplots import make_subplots

In [3]:
p=Props(['Benzene','Toluene'])

In [4]:
def bubbleP(x, T):
    pi= x*p.Pvap(T)
    ptot=np.sum(pi)
    return ptot, pi/ptot

In [15]:
z=np.array([0.4,0.6])

In [16]:
def dewP(y, T):
    P=1/np.sum(y/p.Pvap(T))
    x = y*P/p.Pvap(T)
    return P, x

In [17]:
dewP(z,80+273)

(Array(51140.99477745, dtype=float64),
 Array([0.20363048, 0.79636952], dtype=float64))

In [8]:
bubbleP(z,80+273)

(Array(63301.73149713, dtype=float64),
 Array([0.63479101, 0.36520899], dtype=float64))

In [9]:
p.Pvap(80+273)

Array([100458.42569497,  38530.6020319 ], dtype=float64)

In [11]:
z1s=np.linspace(0,1,11)
zs=np.c_[z1s,1-z1s]

In [12]:
x1s,y1s,bPs,dPs=[],[],[],[]
T=80+273.15
for z in zs:
    bP,y= bubbleP(z,T)
    dP,x = dewP(z,T)
    x1s.append(x[0])
    y1s.append(y[0])
    bPs.append(bP)
    dPs.append(dP)

In [13]:
fig=make_subplots()
fig.add_scatter(x=z1s,y=bPs,name='bubble')
fig.add_scatter(x=z1s,y=dPs,name='dew')
fig.update_layout(width=800,height=600,template='plotly_dark',title='T=353 K')

In [18]:
fig2=make_subplots()
fig2.add_scatter(x=x1s,y=y1s)
fig2.update_layout(width=600,height=600,template='plotly_dark',title='T=353 K')